### ISSUE TITLE
Composer Installing issue on MC 2.2.2 

### ISSUE THREAD

**Issue by rishabhchd19** [magepal/magento2-guest-to-customer#1]
There's a composer error while installing the extension. Apologize but I really don't know why I am facing installing and functioning the Magepal extensions after magento 2.2.0 upgradations. Can you help me installing this using composer?
![2018-01-23_16-15-42](https://user-images.githubusercontent.com/30948461/35271832-4e4d844c-0059-11e8-95f1-aef0e5faf928.jpg)

**Comment by srenon** [comment]
@rishabhchd19 ... Composer is running as PHP v5.6.33.

What version of PHP is installed on your server?

If you are using a managed server, then you should contact support or take a look at

https://laracasts.com/discuss/channels/general-discussion/composer-using-wrong-php-version-1

https://stackoverflow.com/questions/15673334/composer-to-use-newer-version-of-php

**Comment by rishabhchd19** [comment]
I installed 7.1.13. But I have now installed dragging folder into "app>code".

**Comment by srenon** [comment]
Since your composer is not setup correctly, you will not be able to install any module using composer that have any requirement.

```
"require": {
        "php": "~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0",
        "magento/module-backend": "100.0.*|100.1.*|100.2.*",
        "magento/framework": "100.0.*|100.1.*|101.0.*"
    }
```
