### ISSUE TITLE
Error: customer has no tokens

### ISSUE THREAD

**Issue by iphigenie** [magepal/magento2-guest-to-customer#14]
This happens when the "guest to customer" needs to create a customer.

#### Magento version #:

2.3.4-p2

#### Edition (EE, CE, OS, etc):

CE

#### Expected behavior:

Customer is created and the order added to the new customer

#### Actual behavior:

Error messages The customer has no tokens.

The customer is not created but the customer table increment goes up 1 which suggests that the customer creation started far enough to increment, or it was created then reverted when that exception hits

There is only one place that generates this error message and it is revokeCustomerAccessToken in CustomerTokenService

It should not be called on account creation but I think the module creates then updates, and perhaps the update triggers it.

I am looking at the changes in 1.2.6 and can't spot what could trigger this problem so will be looking for conflicts first

module-integration\Plugin\Model\CustomerUser.php is one place
and password reset another

disabling the module makes the error disappear

**Comment by srenon** [comment]
@iphigenie ... sorry I miss this issue. Are you still having issues?

**Comment by iphigenie** [comment]
@srenon I had turned it off and decide to do the upgrades then revisit, in case the bug disappears. Will check on 2.3.5-p2

**Comment by shuffless** [comment]
Tested with 2.3.5-p1 and I have the issue at customer account creation from scratch

![screenshot--2020 12 16-17_30_55](https://user-images.githubusercontent.com/4831785/102369392-8c01cc00-3fc4-11eb-9333-1e2b96f495ed.jpg)

**Comment by srenon** [comment]
@shuffless .... base on the screenshot it seems as if you are trying to create a customer from the frontend, is this correct?

I can not think of a reason this extension would cause that issue, so what is the reason you think this extension is causing that error? 

If you disable this extension do you still have this error?

**Comment by shuffless** [comment]
Solved by editing 

_vendor/magento/module-integration/Model/CustomerTokenService.php_

and at line **118** I added `return true;`

Function was: 

```
public function revokeCustomerAccessToken($customerId)
    {
        $tokenCollection = $this->tokenModelCollectionFactory->create()->addFilterByCustomerId($customerId);
        if ($tokenCollection->getSize() == 0) {
            throw new LocalizedException(__('This customer has no tokens.'));
        }
        try {
            foreach ($tokenCollection as $token) {
                $token->delete();
            }
        } catch (\Exception $e) {
            throw new LocalizedException(__("The tokens couldn't be revoked."));
        }
        return true;
    }

```
Now is 

```
public function revokeCustomerAccessToken($customerId)
    {
		return true;
        $tokenCollection = $this->tokenModelCollectionFactory->create()->addFilterByCustomerId($customerId);
        if ($tokenCollection->getSize() == 0) {
            throw new LocalizedException(__('This customer has no tokens.'));
        }
        try {
            foreach ($tokenCollection as $token) {
                $token->delete();
            }
        } catch (\Exception $e) {
            throw new LocalizedException(__("The tokens couldn't be revoked."));
        }
        return true;
    }
```

**Comment by lukawefocus** [comment]
@shuffless how can this be the solution? ignoring the whole method...

If you answer @srenon's question, it will help fixing the issue much better:

> If you disable this extension do you still have this error? (revert your change in CustomerTokenService.php first)

**Comment by srenon** [comment]
@shuffless... Making that change may solve your issue, but our extension shouldn't even trigger any functionality when creating a new customer. Our extension only gets executed when you click the convert button.

**Comment by iphigenie** [comment]
I haven't seen it happen in recent versions so will close it
