### ISSUE TITLE
About MagePal Catalog Lazy Load Image

### ISSUE THREAD

**Issue by oviliz** [magepal/magento2-guest-to-customer#2]
Nothing major it seems but managing the backend talks about another extension of yours. :)

![screenshot from 2018-02-13 18-54-46](https://user-images.githubusercontent.com/73616/36167959-855bc808-10ef-11e8-9705-d4f92b581797.png)

**Comment by srenon** [comment]
@oviliz .... This was already fixed just need to update the release ... https://github.com/magepal/magento2-guest-to-customer/commit/d94e00d3b74a23e0722a687263b65894ae628dd0

Thanks for the reminder

**Comment by srenon** [comment]
Please upgrade to the latest version 1.1.2

Thanks

**Comment by oviliz** [comment]
Thanks @srenon ! Done the update and all good except that it says Module Version v1.1.0 rather than 1.1.2.

Sorry for being annoying. :)

**Comment by srenon** [comment]
That is intentional... the module version has to do with install script (database table install and changes). So updating the version number will force you to do a setup update, By not changing the version number you can avoid the deploy (in dev and default mode)
