### ISSUE TITLE
Issue if customer has downloadable products

### ISSUE THREAD

**Issue by neha023** [magepal/magento2-guest-to-customer#3]
#### Magento version #:
Magento 2.2.0

#### Edition (EE, CE, OS, etc):
Magento Community Edition

#### Expected behavior:
Downloadable products will shows in My downloads if order contain any.

#### Actual behavior:
If a customer order some downloadable product. Then Sink via putting their order Id in the customer account that order will show in My Orders but Nothing is showing in My Downloads

**Comment by srenon** [comment]
I will have to look into this, not sure when I will have the free time. You are more thank welcome to open a paid support at https://www.magepal.com/magento2/support.html.

But another option would be to 

>  if you wanted to allowed downloadable product along with other product as an guest checkout then you need to set NO to Disable Guest Checkout if Cart Contains Downloadable Items  from store->configuration->catalog->downloadable product option

Pull request is always wecome
