### ISSUE TITLE
 Missing argument 1 for Magento\Sales\Model\Order\CustomerManagement::create(), called in ..../vendor/magento/framework/Interception/Interceptor.php on line 58 and defined in .../vendor/magento/module-sales/Model/Order/CustomerManagement.php on line 73

### ISSUE THREAD

**Issue by psol7** [magepal/magento2-guest-to-customer#4]
#### Actual behavior: error:
 Missing argument 1 for Magento\Sales\Model\Order\CustomerManagement::create(), called in ..../vendor/magento/framework/Interception/Interceptor.php on line 58 and defined in .../vendor/magento/module-sales/Model/Order/CustomerManagement.php on line 73

**Comment by srenon** [comment]
@psol7 ... Please provide more information on which magepal/magento2-guest-to-customer files trigger this error

**Comment by psol7** [comment]
not sure, only that if I disable the module, there is no error.

here is the system log:
main.CRITICAL: Exception message: Warning: Missing argument 1 for Magento\Sales\Model\Order\CustomerManagement::create(), called in .../vendor/magento/framework/Interception/Interceptor.php on line 58 and defined in .../vendor/magento/module-sales/Model/Order/CustomerManagement.php on line 73
Trace: #0 .../vendor/magento/module-sales/Model/Order/CustomerManagement.php(73): Magento\Framework\App\ErrorHandler->handler(2, 'Missing argumen...', ‘/home/...', 73, Array)
#1 .../vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order\CustomerManagement->create()
#2 .../vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\CustomerManagement\Interceptor->___callParent('create', Array)
#3 .../app/code/MagePal/GuestToCustomer/Plugin/Api/OrderCustomerManagementInterfacePlugin.php(38): Magento\Sales\Model\Order\CustomerManagement\Interceptor->Magento\Framework\Interception\{closure}()
#4 .../vendor/magento/framework/Interception/Interceptor.php(135): MagePal\GuestToCustomer\Plugin\Api\OrderCustomerManagementInterfacePlugin->aroundCreate(Object(Magento\Sales\Model\Order\CustomerManagement\Interceptor), Object(Closure), '3759')
#5 .../vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\CustomerManagement\Interceptor->Magento\Framework\Interception\{closure}('3759')
#6 .../generated/code/Magento/Sales/Model/Order/CustomerManagement/Interceptor.php(26): Magento\Sales\Model\Order\CustomerManagement\Interceptor->___callPlugins('create', Array, NULL)
#7 .../vendor/magento/module-checkout/Controller/Account/Create.php(78): Magento\Sales\Model\Order\CustomerManagement\Interceptor->create('3759')
#8 .../generated/code/Magento/Checkout/Controller/Account/Create/Interceptor.php(24): Magento\Checkout\Controller\Account\Create->execute()
#9 .../vendor/magento/framework/App/Action/Action.php(107): Magento\Checkout\Controller\Account\Create\Interceptor->execute()
#10 .../vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#11 .../vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Account\Create\Interceptor->___callParent('dispatch', Array)
#12 .../vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Account\Create\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 .../generated/code/Magento/Checkout/Controller/Account/Create/Interceptor.php(39): Magento\Checkout\Controller\Account\Create\Interceptor->___callPlugins('dispatch', Array, Array)
#14 .../vendor/magento/framework/App/FrontController.php(55): Magento\Checkout\Controller\Account\Create\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 .../vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#16 .../vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#17 .../vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 .../vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 .../app/code/Amasty/Finder/Plugin/FrontController/Redirect.php(79): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 .../vendor/magento/framework/Interception/Interceptor.php(135): Amasty\Finder\Plugin\FrontController\Redirect->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 .../vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 .../vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 .../vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 .../generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 .../vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 .../vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#27 .../index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by srenon** [comment]
What version of our extension are you using?

**Comment by psol7** [comment]
<module name="MagePal_GuestToCustomer" setup_version="1.1.0">

**Comment by psol7** [comment]
1.1.0

**Comment by psol7** [comment]
actually not sure, where can I check for version?

**Comment by psol7** [comment]
downloaded from Master (github) Aug 25

**Comment by srenon** [comment]
Base on the limited information you provide I don't think you are using the latest version our this extension. 

Please update to the latest version and you if need further assistance please open a paid ticket at magepal.com
