### ISSUE TITLE
Required DOB

### ISSUE THREAD

**Issue by Vladekarpa** [magepal/magento2-guest-to-customer#7]
I have required DOB for my site and i cant convert custmer.

**Comment by srenon** [comment]
@Vladekarpa ... during order did the quest enter there DOB?

The only solution I can think of is manually create the customer and then convert the order (this is only available on frontend at the moment)

**Comment by Vladekarpa** [comment]
@srenon I have a new field for DOB for guest checkout and i store it in sales order so i use that for guest, i need when i convert the customer the DOB to take the info from sales order where i have stored DOB.

**Comment by srenon** [comment]
@Vladekarpa ... you will need to write some custom code to append the dob

**Comment by srenon** [comment]
@Vladekarpa ... let me know if the last release fixed your issue
