### ISSUE TITLE
Downloadable products can't be attached

### ISSUE THREAD

**Issue by fffab** [magepal/magento2-guest-to-customer#9]
Hi,
first. thanks for this usefull extension.
my question / issue is
Does this deal with downloadable products ?

it's seems to be follow up from,but this issue but, it seems closed, and the problem still persist.
https://github.com/magepal/magento2-guest-to-customer/issues/3

In my case, a customer can attach a guest order, but if the order contains downloadable products they don't show up in the customer dashboard in the Downloadable Links section.

Here, some details

#### Magento version #:
2.2.8
#### Edition (EE, CE, OS, etc):
CE
#### Expected behavior:
Attach downloaded files to Downloadable files in customer session
#### Actual behavior:
Restore the order, but does not deal with downloadable files
#### Steps to reproduce:
- Order as guest a downloadable product
- Order status complete (M2 option to have the download enable directly)
- Rattach order by the module
- Chek if order is present in customer account (it is, allways)
- Go to Downloadable section in customer dashboard, no link appears

Regards,

**Comment by srenon** [comment]
@fffab ... what version of our extension are you using

**Comment by fffab** [comment]
sorry i did not mention it.
it's latest at this time 1.2.3

**Comment by srenon** [comment]
![image](https://user-images.githubusercontent.com/1415141/56230484-59af0700-604a-11e9-8694-1daf0f61560d.png)

I was not able to reproduce (recreate from admin with pending order)

**Comment by fffab** [comment]
thanks @srenon for your test.
i think the problem is not related to your extension.

I attach a guest order  it allways work fines for downloadable.

the case i mean, is when the order is attach following this workflow
- Guest purchase a downloadable product
- Online payment
- Order state success
- Customer then create the account turning it from Guest to Customer
- Dashboard / My Order contains the new order
- Dashboard My downloadable products contains nothing.

It's more a M2 bug than an issue here. I apologize for that.
But i'm still stuck in this case resolution

Thanks for taking the time and tests.
Regards,

**Comment by srenon** [comment]
Let me know what issue is and I will try to add a workaround... In the meantime this is the code that should show that section https://github.com/magepal/magento2-guest-to-customer/blob/master/Observer/UpdateDownloadableProductObserver.php#L45

**Comment by fffab** [comment]
The clue is in adding this behaviour

- parse 'dowloadable_link_purchased' table by order_increment_id (real order number)
- set customer_id (should be null at this time) to the customer_id just created 

after turning a guest to customer and attached his orders.

**Comment by srenon** [comment]
@fffab ... sorry I have no idea what your last comment mean, have you take a look at the link from my previous post?

**Comment by fffab** [comment]
hi, sorry this was a bit synthetic... i'd tried to explain how to code the missing feature that will allow to make guest order downloadable product available in the dashboard, after guest turned into customer. I will try to submit a PR on this, would be much easier to understand.
